etmodel_uri: http://etmodel.test
etsource_lazy_load_dataset: false
etsource_export: spec/fixtures/etsource
etsource_working_copy: spec/fixtures/etsource

mailchimp:
  list_url: http://mailchimp.test
  api_key: def
